// Command genembed regenerates src/embed_generated.go from
// current-build-version.json.
//
// It reads the "current-build-path" variable (e.g. "paper-server/1.21.11"),
// packs that directory into src/bundled/bundle.tar.gz (gitignored, gzip
// compression), and writes src/embed_generated.go embedding that single
// archive. This is how the "paper" binary is built using the path provided
// in current-build-version.json: go:embed can only embed files inside the
// package directory, so the template is staged under src/bundled/ first; the
// source of truth for WHICH version is staged stays
// current-build-version.json.
//
// Size strategy (measured with gzip -9 on Paper 1.21.11):
//   - paper.jar / cache/*.jar / libraries/*.jar are already zip-compressed,
//     so gzip only shrinks them ~0-8%. Compression is still worth doing for
//     the single-archive packaging, but it is NOT where the savings are.
//   - The savings come from EXCLUDING server-regenerated output:
//     top-level logs/ and versions/ (paperclip re-extracts the version jar
//     from paper.jar on every boot) and plugins/.paper-remapped (plugin
//     remapper cache, rebuilt as needed). This cuts ~60MB with no offline
//     cost: `paper new` output plus one boot reproduces the full tree.
// Everything else (paper.jar, libraries/, cache/, eula.txt,
// server.properties, ...) is bundled, so new servers start with no
// downloads.
//
// Compression is always lossless (gzip = deflate + CRC32): extraction yields
// bit-identical files, and a corrupt archive fails the CRC check instead of
// deploying bad data.
//
// Usage:
//
//	go run ./src/genembed
package main

import (
	"archive/tar"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const versionFileName = "current-build-version.json"

// stagedDir is relative to the repo root.
const stagedDir = "src/bundled"

// archiveName is the single staged artifact embedded into the binary.
const archiveName = "bundle.tar.gz"

// skipRel reports whether a template-relative slash path is excluded from
// the bundle because the server regenerates it on boot (see above).
func skipRel(relSlash string) bool {
	top := strings.Split(relSlash, "/")[0]
	if top == "logs" || top == "versions" {
		return true
	}
	if relSlash == "plugins/.paper-remapped" || strings.HasPrefix(relSlash, "plugins/.paper-remapped/") {
		return true
	}
	return false
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genembed:", err)
		os.Exit(1)
	}
}

func run() error {
	// src/genembed -> repo root is two levels up.
	root, err := filepath.Abs(filepath.Join(".", "..", ".."))
	if err != nil {
		return err
	}
	// Allow running from repo root too: if current dir holds the json, use it.
	if _, err := os.Stat(filepath.Join(".", versionFileName)); err == nil {
		root, _ = filepath.Abs(".")
	}
	versionPath := filepath.Join(root, versionFileName)
	raw, err := os.ReadFile(versionPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", versionPath, err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return fmt.Errorf("parse %s: %w", versionPath, err)
	}
	buildPath, _ := decoded["current-build-path"].(string)
	buildPath = strings.TrimSpace(buildPath)
	if buildPath == "" {
		return fmt.Errorf("%s: missing \"current-build-path\"", versionPath)
	}
	buildPathSlash := filepath.ToSlash(buildPath)

	absBuild := filepath.Join(root, filepath.FromSlash(buildPathSlash))
	if st, err := os.Stat(filepath.Join(absBuild, "paper.jar")); err != nil || st.IsDir() {
		return fmt.Errorf("paper.jar not found at %s (from current-build-path=%q)", filepath.Join(absBuild, "paper.jar"), buildPathSlash)
	}

	// Stage the archive inside the src package dir, because //go:embed can
	// only embed files in the package directory or subdirectories.
	stagedAbs := filepath.Join(root, filepath.FromSlash(stagedDir))
	if err := os.RemoveAll(stagedAbs); err != nil {
		return fmt.Errorf("clear %s: %w", stagedAbs, err)
	}
	if err := os.MkdirAll(stagedAbs, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", stagedAbs, err)
	}
	archivePath := filepath.Join(stagedAbs, archiveName)
	out, err := os.Create(archivePath)
	if err != nil {
		return fmt.Errorf("create %s: %w", archivePath, err)
	}
	gz, err := gzip.NewWriterLevel(out, gzip.BestCompression)
	if err != nil {
		out.Close()
		return err
	}
	tw := tar.NewWriter(gz)
	files, totalBytes, err := writeBundle(absBuild, tw)
	closeErr := tw.Close()
	gzCloseErr := gz.Close()
	outCloseErr := out.Close()
	if err != nil {
		return err
	}
	for _, cerr := range []error{closeErr, gzCloseErr, outCloseErr} {
		if cerr != nil {
			return fmt.Errorf("finalize archive: %w", cerr)
		}
	}
	st, _ := os.Stat(archivePath)

	version := filepath.ToSlash(filepath.Base(buildPathSlash))

	content := fmt.Sprintf(`// Code generated by src/genembed from %s. DO NOT EDIT.
// Regenerate with: go run ./src/genembed
// Source build path: %s (packed into src/bundled/%s at build time;
// regenerable logs/, versions/ and plugins/.paper-remapped excluded)
package src

import _ "embed"

//go:embed bundled/%s
var bundledArchive []byte

// EmbeddedBuildPath is the value of "current-build-path" the binary was built with.
const EmbeddedBuildPath = %q

// EmbeddedVersion is the base name of EmbeddedBuildPath (e.g. "1.21.11").
const EmbeddedVersion = %q

// EmbeddedFileCount is the number of template files in the archive.
const EmbeddedFileCount = %d

// EmbeddedUncompressedBytes is the total size of the template files.
const EmbeddedUncompressedBytes = %d

// EmbeddedArchiveBytes is the compressed archive size.
const EmbeddedArchiveBytes = %d

// EmbeddedHasEula is true when the template dir contained an eula.txt at build time.
const EmbeddedHasEula = %t

// EmbeddedHasServerProps is true when the template dir contained a server.properties at build time.
const EmbeddedHasServerProps = %t
`,
		versionFileName, buildPathSlash, archiveName, archiveName,
		buildPathSlash, version, files, totalBytes, st.Size(),
		hasTemplate(absBuild, "eula.txt"), hasTemplate(absBuild, "server.properties"),
	)

	outPath := filepath.Join(root, "src", "embed_generated.go")
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("genembed: packed %s (%d files, %.1f MB -> %.1f MB archive, version %s) -> src/bundled/%s\n",
		buildPathSlash, files, float64(totalBytes)/1048576, float64(st.Size())/1048576, version, archiveName)
	return nil
}

// writeBundle tars absBuild (minus skipped paths), preserving empty dirs as
// explicit entries. It returns the file count and uncompressed byte total.
func writeBundle(absBuild string, tw *tar.Writer) (int, int64, error) {
	var files int
	var totalBytes int64
	err := filepath.WalkDir(absBuild, func(src string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(absBuild, src)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		relSlash := filepath.ToSlash(rel)
		if skipRel(relSlash) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return tw.WriteHeader(&tar.Header{
				Name:     relSlash + "/",
				Typeflag: tar.TypeDir,
				Mode:     0o755,
			})
		}
		if !d.Type().IsRegular() {
			return fmt.Errorf("unsupported non-regular file in template: %s", src)
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if err := tw.WriteHeader(&tar.Header{
			Name:     relSlash,
			Typeflag: tar.TypeReg,
			Mode:     0o644,
			Size:     info.Size(),
		}); err != nil {
			return err
		}
		f, err := os.Open(src)
		if err != nil {
			return err
		}
		if _, err := io.Copy(tw, f); err != nil {
			f.Close()
			return fmt.Errorf("archive %s: %w", src, err)
		}
		f.Close()
		files++
		totalBytes += info.Size()
		return nil
	})
	return files, totalBytes, err
}

func hasTemplate(absBuild, name string) bool {
	_, err := os.Stat(filepath.Join(absBuild, name))
	return err == nil
}
