// Command genembed regenerates src/embed_generated.go from
// current-build-version.json.
//
// It reads the "current-build-path" variable (e.g. "paper-server/1.21.11"),
// copies paper.jar (+ optional eula.txt / server.properties) into
// src/bundled/ (gitignored), and writes src/embed_generated.go with a
// //go:embed directive for exactly that content. This is how the "paper"
// binary is built using the path provided in current-build-version.json:
// go:embed can only embed files inside the package directory, so the
// template is staged under src/bundled/ first; the source of truth for
// WHICH version is staged stays current-build-version.json.
//
// Usage:
//
//	go run ./src/genembed
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const versionFileName = "current-build-version.json"

// stagedDir is relative to the repo root.
const stagedDir = "src/bundled"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genembed:", err)
		os.Exit(1)
	}
}

func run() error {
	// src/genembed -> repo root is two levels up.
	root, err := filepath.Abs(filepath.Join(".", "..", ".."))
	if err != nil {
		return err
	}
	// Allow running from repo root too: if current dir holds the json, use it.
	if _, err := os.Stat(filepath.Join(".", versionFileName)); err == nil {
		root, _ = filepath.Abs(".")
	}
	versionPath := filepath.Join(root, versionFileName)
	raw, err := os.ReadFile(versionPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", versionPath, err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return fmt.Errorf("parse %s: %w", versionPath, err)
	}
	buildPath, _ := decoded["current-build-path"].(string)
	buildPath = strings.TrimSpace(buildPath)
	if buildPath == "" {
		return fmt.Errorf("%s: missing \"current-build-path\"", versionPath)
	}
	buildPathSlash := filepath.ToSlash(buildPath)

	absBuild := filepath.Join(root, filepath.FromSlash(buildPathSlash))
	jarAbs := filepath.Join(absBuild, "paper.jar")
	if _, err := os.Stat(jarAbs); err != nil {
		return fmt.Errorf("paper.jar not found at %s (from current-build-path=%q)", jarAbs, buildPathSlash)
	}

	// Stage the template inside the src package dir, because //go:embed can
	// only embed files in the package directory or subdirectories.
	stagedAbs := filepath.Join(root, filepath.FromSlash(stagedDir))
	if err := os.MkdirAll(stagedAbs, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", stagedAbs, err)
	}
	if err := copyFile(jarAbs, filepath.Join(stagedAbs, "paper.jar")); err != nil {
		return err
	}

	// Optional template files: stage + embed them when present, otherwise
	// the CLI falls back to generated defaults at `paper new` time.
	var extra []string
	for _, name := range []string{"eula.txt", "server.properties"} {
		if _, err := os.Stat(filepath.Join(absBuild, name)); err == nil {
			if err := copyFile(filepath.Join(absBuild, name), filepath.Join(stagedAbs, name)); err != nil {
				return err
			}
			extra = append(extra, name)
		} else {
			_ = os.Remove(filepath.Join(stagedAbs, name)) // stale from previous version
		}
	}

	version := filepath.ToSlash(filepath.Base(buildPathSlash))

	embedLines := []string{"bundled/paper.jar"}
	for _, e := range extra {
		embedLines = append(embedLines, "bundled/"+e)
	}
	embedDirective := "//go:embed " + strings.Join(embedLines, " ")

	hasEula := contains(extra, "eula.txt")
	hasProps := contains(extra, "server.properties")

	content := fmt.Sprintf(`// Code generated by src/genembed from %s. DO NOT EDIT.
// Regenerate with: go run ./src/genembed
// Source build path: %s (staged into src/bundled/ at build time)
package src

import "embed"

%s
var bundledFS embed.FS

// EmbeddedBuildPath is the value of "current-build-path" the binary was built with.
const EmbeddedBuildPath = %q

// EmbeddedVersion is the base name of EmbeddedBuildPath (e.g. "1.21.11").
const EmbeddedVersion = %q

// EmbeddedHasEula is true when the template dir contained an eula.txt at build time.
const EmbeddedHasEula = %t

// EmbeddedHasServerProps is true when the template dir contained a server.properties at build time.
const EmbeddedHasServerProps = %t
`,
		versionFileName, buildPathSlash, embedDirective, buildPathSlash, version, hasEula, hasProps,
	)

		outPath := filepath.Join(root, "src", "embed_generated.go")
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("genembed: staged %s (version %s) -> src/bundled/ + src/embed_generated.go\n", buildPathSlash, version)
	return nil
}

func copyFile(from, to string) error {
	in, err := os.Open(from)
	if err != nil {
		return fmt.Errorf("open %s: %w", from, err)
	}
	defer in.Close()
	out, err := os.Create(to)
	if err != nil {
		return fmt.Errorf("create %s: %w", to, err)
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return fmt.Errorf("copy %s -> %s: %w", from, to, err)
	}
	if err := out.Close(); err != nil {
		return fmt.Errorf("close %s: %w", to, err)
	}
	return nil
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}
