// Code generated by src/genembed from current-build-version.json. DO NOT EDIT.
// Regenerate with: go run ./src/genembed
// Source build path: paper-server/1.21.11 (packed into src/bundled/bundle.tar.gz at build time;
// regenerable logs/, versions/ and plugins/.paper-remapped excluded)
package src

import _ "embed"

//go:embed bundled/bundle.tar.gz
var bundledArchive []byte

// EmbeddedBuildPath is the value of "current-build-path" the binary was built with.
const EmbeddedBuildPath = "paper-server/1.21.11"

// EmbeddedVersion is the base name of EmbeddedBuildPath (e.g. "1.21.11").
const EmbeddedVersion = "1.21.11"

// EmbeddedFileCount is the number of template files in the archive.
const EmbeddedFileCount = 118

// EmbeddedUncompressedBytes is the total size of the template files.
const EmbeddedUncompressedBytes = 187554431

// EmbeddedArchiveBytes is the compressed archive size.
const EmbeddedArchiveBytes = 181735795

// EmbeddedHasEula is true when the template dir contained an eula.txt at build time.
const EmbeddedHasEula = true

// EmbeddedHasServerProps is true when the template dir contained a server.properties at build time.
const EmbeddedHasServerProps = true
