// Code generated by src/genembed from current-build-version.json. DO NOT EDIT.
// Regenerate with: go run ./src/genembed
// Source build path: paper-server/1.21.11 (mirrored into src/bundled/ at build time;
// top-level logs/ excluded as regenerable runtime output)
package src

import "embed"

//go:embed all:bundled
var bundledFS embed.FS

// EmbeddedBuildPath is the value of "current-build-path" the binary was built with.
const EmbeddedBuildPath = "paper-server/1.21.11"

// EmbeddedVersion is the base name of EmbeddedBuildPath (e.g. "1.21.11").
const EmbeddedVersion = "1.21.11"

// EmbeddedFileCount is the number of template files bundled.
const EmbeddedFileCount = 121

// EmbeddedHasEula is true when the template dir contained an eula.txt at build time.
const EmbeddedHasEula = true

// EmbeddedHasServerProps is true when the template dir contained a server.properties at build time.
const EmbeddedHasServerProps = true

// bundledEmptyDirs lists template dirs that were empty at build time
// (go:embed drops empty dirs, so paper new recreates these).
var bundledEmptyDirs = []string{"plugins/.paper-remapped/extra-plugins", "plugins/.paper-remapped/libraries", "plugins/.paper-remapped/unknown-origin"}
